version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=messages
      - POSTGRES_USER=messages
      - POSTGRES_PASSWORD=messages
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - '5437:5432'
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == school-example-1

  chat:
    image: cr.yandex/crp3g2ebtfsh3buhv6q0/dockerimagedemo:0.0.16
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: messages
      DB_PASSWORD: messages
      DB_NAME: messages
    ports:
      - '80:8080'
    deploy:
      replicas: 3

volumes:
  db:
    driver: local
