version: '3.8'

services:
  db:
    hostname: db
    container_name: db
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=messages
      - POSTGRES_USER=messages
      - POSTGRES_PASSWORD=messages
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - '5437:5432'

  chat:
    hostname: chat
    container_name: chat
    image: cr.yandex/crp3g2ebtfsh3buhv6q0/dockerimagedemo:0.0.15
    restart: always
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: messages
      DB_PASSWORD: messages
      DB_NAME: messages
    ports:
      - '80:8080'

volumes:
  db:
    driver: local
