---
- name: Deploy to swarm
  hosts: worker_node

  tasks:
  - name: Auth to Cloud Registry
    become: true
    ansible.builtin.raw: docker login --username oauth --password y0_AgAAAAAcLcNaAATuwQAAAAD6kJuXAADV7-ekdjNExrRqIw3h85lPb94i6Q cr.yandex

  - name: Pull postgress image
    community.docker.docker_image:
      name: postgres
      source: pull

  - name: Pull dockerimagedemo image
    community.docker.docker_image:
      name: cr.yandex/crp3g2ebtfsh3buhv6q0/dockerimagedemo:0.0.16
      source: pull
