---
- name: Deploy dockerimagedemo
  hosts: app_hosts

  tasks:
  - name: Copy docker-compose file to remote
    become: true
    ansible.builtin.copy:
      src: /Users/web.varlamov/IdeaProjects/dockerimagedemo/prod_env
      dest: /home/webvarlamov/dockerimagedemo

  - name: Auth to Cloud Registry
    become: true
    ansible.builtin.raw: curl -H Metadata-Flavor:Google 169.254.169.254/computeMetadata/v1/instance/service-accounts/default/token | cut -f1 -d',' | cut -f2 -d':' | tr -d '"' | docker login --username iam --password-stdin cr.yandex

  - name: Docker compose down
    become: true
    ansible.builtin.raw: docker-compose --file /home/webvarlamov/dockerimagedemo/prod_env/docker-compose.yaml down

  - name: Docker compose up
    become: true
    ansible.builtin.raw: docker-compose --file /home/webvarlamov/dockerimagedemo/prod_env/docker-compose.yaml up -d




