---
- name: Deploy dockerimagedemo
  hosts: app_hosts

  tasks:
  - name: Copy docker-compose file to remote
    become: true
    ansible.builtin.copy:
      src: /Users/web.varlamov/IdeaProjects/dockerimagedemo/prod_env
      dest: /home/webvarlamov/dockerimagedemo

  - name: Auth to Cloud Registry
    become: true
    ansible.builtin.raw: docker login --username oauth --password y0_AgAAAAAcLcNaAATuwQAAAADePotPnbNvOqaoSbi5kwmM6u538Kc4Ke0 cr.yandex

  - name: Docker compose down
    become: true
    ansible.builtin.raw: docker-compose --file /home/webvarlamov/dockerimagedemo/prod_env/docker-compose.yaml down

  - name: Docker compose up
    become: true
    ansible.builtin.raw: docker-compose --file /home/webvarlamov/dockerimagedemo/prod_env/docker-compose.yaml up -d




